steps:
# Starter pipeline
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'nearavenac-devops'
    projectKey: 'nearavenac-devops_spring-boot-kubernetes'
    projectName: 'spring-boot-kubernetes'
- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'nearavenac-devops'
